version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/data.json:/app/data.json
    environment:
      FLASK_APP: backend
      FLASK_ENV: development

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"