version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/app/data.json:/app/data.json

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"